# aipipeline/projects/planktivore/config_lowmag.yml
# Config file for Planktivore project log mag images

config_url: "https://docs.mbari.org/internal/ai/projects/config/config_planktivore_lm.yml"

data:
  download_args: "--verified --version mbari-ifcb2014-vitb16-20250318_20250320_002422"
  download_dir: "/mnt/ML_SCRATCH/data/ptrv_lm"
  cleanvision_issues:
    - name: "low_information"
      threshold: 0.53
    - name: "blurry"
    - name: "dark"
    - name: "exact_duplicates"

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"
