# aipipeline/projects/planktivore/config_highmag.yml
# Config file for Planktivore project high mag images

config_url: "https://docs.mbari.org/internal/ai/projects/config/config_planktivore_hm.yml"

data:
  download_args: "--verified --version mbari-ptvr-vits-b8-20250513_20250526_130025,mbari-ifcb2014-vitb16-20250318_20250320_025000"
  download_dir: "/mnt/ML_SCRATCH/data/ptrv_hm"
  cleanvision_issues:
    - name: "dark"
    - name: "exact_duplicates"

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"