# aipipeline/projects/biodiversity/config.yml
# Config file for Bio project production
redis:
  host: "doris.shore.mbari.org"
  port: 6380

data:
  processed_path: "/mnt/ML_SCRATCH/901103-biodiversity"
  version: "mega-vits-track-gcam"
  labels: "all"
  download_args: ["--verified --min-saliency 1000"]

mounts:
  - name: "video"
    path: "/mnt/M3"
    host: "m3.shore.mbari.org"
    nginx_root: "/M3"

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"

vss:
  project: "901103-biodiversity"
  threshold: 0.1
  model: "google/vit-base-patch16-224"

tator:
  project: "901103-biodiversity"
  host: "mantis.shore.mbari.org"
  url_load: "http://mantis.shore.mbari.org:8001/label/id"

  image:
    attributes:
      date:
        type: string
      time:
        type: string

  video:
    attributes:
      video_reference_uuid:
        type: string
      iso_start_datetime:
        type: datetime

  box:
    attributes:
      Label:
        type: string
      label_s:
        type: string
      concept:
        type: string
      score:
        type: float
      score_s:
        type: float
      cluster:
        type: string
      saliency:
        type: float
      group:
        type: string
      obs_uuid:
        type: string
      exemplar:
        type: bool
      verified:
        type: bool


ffmpeg_path: "/usr/bin/ffmpeg"
