# aipipeline/projects/biodiversity/config.yml
# Config file for Bio project production
redis:
  host: "doris.shore.mbari.org"
  port: 6381

data:
  processed_path: "/mnt/ML_SCRATCH/901103-biodiversity"
  version: "Baseline"
  #labels: "Aegina citrea,Aegina rosea,Aegina sp. 1,Aglantha,Aglantha digitale,Beroe,Beroe abyssicola,Beroe forskalii,Beroe gracilis,Colobonema,Colobonema sericeum,Merluccius productus,Pantachogon,Pantachogon haeckeli,Praya dubia,Praya dubia nectosome,Teuthoidea,Thalassocalyce,Thalassocalyce inconstans,Vampyroteuthis infernalis,Vitreosalpa gemini,larvacean house,larvacean house outer filter"
  labels: "Ctenophora sp. A"
  download_args: ["--verified"]

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"

vss:
  project: "901103-biodiversity"
  threshold: 0.9
  model: "google/vit-base-patch16-224"

tator:
  project: "901103-biodiversity"
  host: "mantis.shore.mbari.org"
  url_load: "http://mantis.shore.mbari.org:8001/label/id"

  image:
    attributes:
      date:
        type: string
      time:
        type: string

  box:
    attributes:
      Label:
        type: string
      concept:
        type: string
      score:
        type: float
      cluster:
        type: string
      saliency:
        type: float
      group:
        type: string
      obs_uuid:
        type: string
      exemplar:
        type: bool
      verified:
        type: bool


ffmpeg_path: "/usr/bin/ffmpeg"
