# aipipeline/projects/i2map/config.yml
# Config file for i2map project production
redis:
  host: "doris.shore.mbari.org"
  port: 6380

data:
  processed_path: "/mnt/ML_SCRATCH/i2map"
#  version: "vss_vits14_all"
  version2: "dino_vits8_20240207_022529"
  version: "Baseline"
  labels: "Acanthamunnopsis miller,Bathochordaeus sinker,Bolinopsis,Cydippida,Eusergestes similis,Solmissus,Actinopterygii,Pyrosoma,Salpa fusiformis,krill molt,Merluccius productus,Radiozoa,Thalassocracy inconstans"
  download_args: ["--verified"]

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"

vss:
  project: "i2map"
  threshold: 0.80
  model: "google/vit-base-patch16-224"

tator:
  project: "i2map"
  host: "i2map.shore.mbari.org"
  url_load: "http://i2map.shore.mbari.org:8001/label/id"

  image:
    attributes:
      iso_datetime:
        type: string
      depth:
        type: int

  box:
    attributes:
      Label:
        type: string
      concept:
        type: string
      score:
        type: float
      cluster:
        type: string
      saliency:
        type: float
      group:
        type: string
      obs_uuid:
        type: string
      exemplar:
        type: bool
      verified:
        type: bool


ffmpeg_path: "/usr/bin/ffmpeg"
