# aipipeline/projects/i2map/config.yml
# Config file for i2map project production
redis:
  host: "doris.shore.mbari.org"
  port: 6380

data:
  processed_path: "/mnt/ML_SCRATCH/i2mapbulk"
  processed_path_sdcat: "/mnt/ML_SCRATCH/i2mapbulkprocessed"
  version: ""
  labels: "all"
  download_args: ["--verified"]
  load_min_score: 0.7
  cleanvision_issues:
    - name: "low_information"
      threshold: 0.5

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"

vss:
  project: "i2map"
  threshold: 0.1
  model: "/mnt/DeepSea-AI/models/i2MAP/mbari-i2map-vits-b-8-20250216"

tator:
  project: "i2map"
  host: "i2map.shore.mbari.org"
  url_load: "http://i2map.shore.mbari.org:8001/label/id"

  image:
    attributes:
      iso_datetime:
        type: string
      depth:
        type: int

  box:
    attributes:
      Label:
        type: string
      score:
        type: float
      cluster:
        type: string
      verified:
        type: bool
      delete:
        type: bool


ffmpeg_path: "/usr/bin/ffmpeg"

plugins:
  - name: "extractor"
    module: "aidata.plugins.extractors.tap_i2map_media"
    function: "extract_media"
