# aipipeline/projects/uav/config.yml
# Config file for UAV project production

config_url: "https://docs.mbari.org/internal/ai/projects/config/config_uav.yml"

sdcat:
  model: "/mnt/DeepSea-AI/models/UAV/mbari-uav-vits-b-8-20250202/"
  ini: "sdcat.ini"