# aipipeline/projects/uav/config.yml
# Config file for UAV project production
redis:
  host: "doris.shore.mbari.org"
  port: 6379

docker:
  bind_volumes:
    /mnt/UAV:
      bind: /mnt/UAV
      mode: rw
    /mnt/DeepSea-AI:
      bind: /mnt/DeepSea-AI
      mode: ro

mounts:
  - name: "image"
    path: "/mnt/UAV"
    host: "mantis.shore.mbari.org"
    nginx_root: "/UAV"

data:
  raw_path: "/mnt/UAV/"
  processed_path_sdcat: "/mnt/UAV/machineLearning/"
  processed_path: "/mnt/ML_SCRATCH/UAV/"
  version: ""
  labels: "all"
  download_args: ["--verified"]
  load_min_score: 0.7
  cleanvision_issues:
    - name: "low_information"
      threshold: 0.53
    - name: "blurry"
    - name: "dark"
    - name: "exact_duplicates"
    - name: "near_duplicates"

sdcat:
  ini: "sdcat.ini"
  detect_args:
    - "--scale-percent"
    - "100"
    - "--model"
    - "/mnt/DeepSea-AI/models/UAV/mbari-uav-yolo11x-jelly/"
    - "--model-type"
    - "ultralytics"
    - "--slice-size-width"
    - "640"
    - "--slice-size-height"
    - "640"
    - "--conf"
    - "0.005"
    - "--skip-saliency"
  cluster_args:
    - "--skip-visualization"
    - "--use-vits"
vss:
  project: "901902-uavs"
  threshold: 0.1
  model: "google/vit-base-patch16-224"

tator:
  project: "901902-uavs"
  host: "mantis.shore.mbari.org"

  image:
    attributes:
      FileType:
        type: string
      date:
        type: string
      time:
        type: string
      latitude:
        type: float
      longitude:
        type: float
      make:
        type: string
      model:
        type: string

  box:
    attributes:
      Label:
        type: string
      score:
        type: float
      cluster:
        type: string
      saliency:
        type: float
      area:
        type: int
      exemplar:
        type: bool
      verified:
        type: bool

plugins:
  - name: "extractor"
    module: "aidata.plugins.extractors.tap_sony_media"
    function: "extract_media"