# aipipeline/projects/i2map/config.yml
# Config file for i2map project production
redis:
  host: "doris.shore.mbari.org"
  port: 6380

data:
  processed_path: "/mnt/ML_SCRATCH/i2map"
  version: "Baseline"
  labels: "all"
  download_args: ["--group NMS --verified"]

sdcat:
  model: "hustvl/yolos-tiny"
  clu_det_ini: "sdcat_clu_det.ini"
  exemplar_ini: "sdcat_exemplar.ini"

vss:
  project: "i2map"
  threshold: 0.4

tator:
  project: "901103-biodiversity"
  host: "mantis.shore.mbari.org"
  bulk_url: "http://mantis.shore.mbari.org:8001/label/id"

  image:
    attributes:
      date:
        type: string
      time:
        type: string

  box:
    attributes:
      Label:
        type: string
      concept:
        type: string
      score:
        type: float
      cluster:
        type: string
      saliency:
        type: float
      group:
        type: string
      obs_uuid:
        type: string
      exemplar:
        type: bool
      verified:
        type: bool


ffmpeg_path: "/usr/bin/ffmpeg"
