# aipipeline/projects/i2map/config.yml
# Config file for BioDiversity Project Production
config_url: "https://docs.mbari.org/internal/ai/projects/config/config_i2map.yml"

data:
  cleanvision_issues:
    - name: "low_information"
      threshold: 0.5

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"