# aipipeline/projects/cfe/config.yml
# Config file for CFE project production

config_url: "https://docs.mbari.org/internal/ai/projects/config/config_cfe_deploy.yml"

data:
  cleanvision_issues:
    - name: "low_information"
      threshold: 0.53
    - name: "blurry"
    - name: "dark"
    - name: "exact_duplicates"

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"
