# aipipeline/projects/cfe/config.yml
# Config file for CFE project production

redis:
  host: "doris.shore.mbari.org"
  port: 6382

docker:
  bind_volumes:
   /mnt/CFElab:
     bind: /mnt/CFElab
     mode: ro

data:
  raw_data_path: "/mnt/CFElab/"
  processed_path: "/mnt/ML_SCRATCH/902111-CFE-Deployments"
  version: "cfe_isiis_final-20250509"
  labels: "all"
  download_args: ["--verified"]
  cleanvision_issues:
    - name: "low_information"
      threshold: 0.53
    - name: "blurry"
    - name: "dark"
    - name: "exact_duplicates"

sdcat:
  model: "hustvl/yolos-tiny"
  ini: "sdcat.ini"

vss:
  project: "902111-CFE-Deployments"
  threshold: 0.8
  model: "google/vit-base-patch16-224"

mounts:
  - name: "image"
    path: "/mnt/CFElab"
    host: "https://mantis.shore.mbari.org"
    nginx_root: "/CFElab"

  - name: "video"
    path: "/mnt/CFElab"
    host: "https://mantis.shore.mbari.org"
    nginx_root: "/CFElab"

tator:
  project: "902111-CFE-Deployments"
  host: "https://mantis.shore.mbari.org"
  url_load: "http://mantis.shore.mbari.org:8001/label/id"
  image:
    attributes:
      iso_datetime:
        type: datetime
      depth:
        type: float
  video:
    attributes:
      iso_datetime:
        type: datetime
      iso_start_datetime:
        type: datetime
      instrument:
        type: enum

  box:
    attributes:
      Label:
        type: string
      score:
        type: float
      score_s:
        type: float
      label_s:
        type: string
      cluster:
        type: string
      saliency:
        type: float
      area:
        type: int
      depth:
        type: float

plugins:
  - name: "extractor"
    module: "mbari_aidata.plugins.extractors.tap_cfe_media"
    function: "extract_media"
