#!/bin/bash
# set -x
time conda run -n m3-download  m3-download generate --include-concept Tuscaroridae \
--include-concept Appendicularia \
--include-concept Euphausiacea \
--include-concept Chaetognatha \
--include-concept 'Krill molt' \
--include-concept 'Eusergestes similis' \
--include-concept Actinopterygii \
--include-concept Copepoda \
--include-concept 'Nanomia bijuga' \
--include-concept Pyrosoma \
--include-concept Beroe \
--include-concept Aegina \
--include-concept 'Hastigerinella digitata' \
--include-concept 'Poeobius meseres' \
--include-concept Calycophorae \
--include-concept Medusae \
--include-concept Solmaris \
--include-concept Cydippida \
--include-concept 'Vitreosalpa gemini' \
--include-concept Mysida \
--include-concept 'Pelagobia longicirrata' \
--include-concept Nanomia \
--include-concept Radiozoa \
--include-concept 'Chuniphyes multidentata' \
--include-concept Solmissus \
--include-concept Myctophidae \
--include-concept 'Thalassocalyce inconstans' \
--include-concept Salpida \
--include-concept Siphonophorae \
--include-concept 'Lensia conoidea' \
--include-concept Crustacea \
--include-concept sinker \
--include-concept 'Earleria corachloeae' \
--include-concept Pasiphaea \
--include-concept Physonectae \
--include-concept 'Haliscera conica' \
--include-concept Amphipoda \
--include-concept Bathochordaeus \
--include-concept Prayidae \
--include-concept 'Caecosagitta macrocephala' \
--include-concept 'Merluccius productus' \
--include-concept Dolioletta \
--include-concept 'Acanthamunnopsis milleri' \
--include-concept 'Liriope tetraphylla' \
--include-concept Apolemia \
--include-concept 'Mitrocoma cellularia' \
--include-concept Thalassocalyce \
--include-concept Polychaeta \
--include-concept 'Bathochordaeus sinker' \
--include-concept object \
--include-concept Cyclosalpa \
--include-concept Ctenophora \
--include-concept Cyclothone \
--include-concept Gonatus \
--include-concept Euphausia \
--include-concept Beroida \
--include-concept Lobata \
--include-concept 'Prayidae sp. 1' \
--include-concept 'Colobonema sericeum' \
--include-concept Atolla \
--include-concept 'Cydippida sp. A' \
--include-concept 'Hormiphora californensis' \
--include-concept 'Bolinopsis infundibulum' \
--include-concept Euchirella \
--include-concept 'Melanostigma pammelas' \
--include-concept 'Solmundella bitentaculata' \
--include-concept Teuthoidea \
--include-concept Lensia \
--include-concept 'Leuroglossus stilbius' \
--include-concept Doliolidae \
--include-concept Doliolida \
--include-concept Tomopteridae \
--include-concept 'Mertensiidae sp. A' \
--include-concept Procymbulia \
--include-concept Sergestidae \
--include-concept Ostracoda \
--include-concept 'Chiroteuthis calyx' \
--include-concept Tomopteris \
--include-concept 'Sergestid molt' \
--include-concept 'Chrysaora fuscescens' \
--include-concept Chuniphyes \
--include-concept 'Gymnopraia lapislazula' \
--include-concept Earleria \
--include-concept 'Pantachogon haeckeli' \
--include-concept 'Nanomia 2' \
--include-concept Bathocyroe \
--exclude-group 'ROV:pending-verifications' \
--exclude-activity 'unspecified' \
--exclude-project 'ML-Tracking' \
--include-descendants \
/mnt/ML_SCRATCH/M3/images /mnt/ML_SCRATCH/M3/xml