import subprocess

ConceptToPhylum = {
#'ConceptName'                   : 'GROUP',
'Acantharea'                    : 'Acantharea',
'Caryophylliina'                : 'Annelida',
'Saxipendium sp. 1'             : 'Annelida',
'Fritillaria'                   : 'Appendicularia',
'Fritillariidae'                : 'Appendicularia',
'Appendicularia'                : 'Appendicularia',
'Bathochordaeinae'              : 'Appendicularia',
'Bathochordaeus'                : 'Appendicularia',
'Bathochordaeus sp. a'          : 'Appendicularia',
'Mesochordaeus erythrocephalus' : 'Appendicularia',
'Mesoikopleura'                 : 'Appendicularia',
'Oikopleura'                    : 'Appendicularia',
'Oikopleura villafrancae'       : 'Appendicularia',
'Oikopleuridae'                 : 'Appendicularia',
'Megalodicopia hians'           : 'Ascidiacea',
'Octacnemidae'                  : 'Ascidiacea',
'Culeolus'                      : 'Ascidiacea',
'Bacillariophyceae'             : 'Bacillariophyta',
'Brachiopoda'                   : 'Brachiopoda',
'Bathyteuthis berryi'           : 'Cephalopoda',
'Chiroteuthis calyx'            : 'Cephalopoda',
'Cirrata'                       : 'Cephalopoda',
'Cranchiidae'                   : 'Cephalopoda',
'Doryteuthis opalescens'        : 'Cephalopoda',
'Dosidicus gigas'               : 'Cephalopoda',
'Galiteuthis'                   : 'Cephalopoda',
'Galiteuthis phyllura'          : 'Cephalopoda',
'Galiteuthis pacifica'          : 'Cephalopoda',
'Gonatidae'                     : 'Cephalopoda',
'Gonatus'                       : 'Cephalopoda',
'Gonatus onyx'                  : 'Cephalopoda',
'Histioteuthis heteropsis'      : 'Cephalopoda',
'Octopoteuthis deletron'        : 'Cephalopoda',
'Planctoteuthis oligobessa'     : 'Cephalopoda',
'Taoniinae'                     : 'Cephalopoda',
'Taonius'                       : 'Cephalopoda',
'Teuthoidea'                    : 'Cephalopoda',
'Benthoctopus'                  : 'Cephalopoda',
'Benthoctopus sp. A'            : 'Cephalopoda',
'Cephalopoda'                   : 'Cephalopoda',
'Gonatus berryi'                : 'Cephalopoda',
'Graneledone boreopacifica'     : 'Cephalopoda',
'Japetella diaphana'            : 'Cephalopoda',
'Vampyroteuthis infernalis'     : 'Cephalopoda',
'Vampyroteuthidae'              : 'Cephalopoda',
'Octopus'                       : 'Cephalopoda',
'Octopus rubescens'             : 'Cephalopoda',
'Onychoteuthis sp.'             : 'Cephalopoda',
'Chaetognatha'                  : 'Chaetognatha',
'Caecosagitta macrocephala'     : 'Chaetognatha',
'Pseudosagitta'                 : 'Chaetognatha',
'Pseudosagitta lyra'            : 'Chaetognatha',
'Pseudosagitta maxima'          : 'Chaetognatha',
'Sagitta'                       : 'Chaetognatha',
'Bathyspadella'                 : 'Chaetognatha',
'Eukrohnia'                     : 'Chaetognatha',
'Eukrohnia fowleri'             : 'Chaetognatha',
'Intacta'                       : 'Ctenophora',
'Heterokrohnia'                 : 'Chaetognatha',
'Chlorophycota'                 : 'Chlorophycota',
'Otariidae'                     : 'Pinnipedia',
'Hydroida'                      : 'Cnidaria',
'Bathycrinidae'                 : 'Crinoidea',
'Tonrometra'                    : 'Crinoidea',
'Hyocrinus'                     : 'Crinoidea',
'Crinoidea'                     : 'Crinoidea',
'Acanthamunnopsis'              : 'Crustacea',
'Acanthamunnopsis milleri'      : 'Crustacea',
'Amphipoda'                     : 'Crustacea',
'Brachyura'                     : 'Crustacea',
'Caridea'                       : 'Crustacea',
'Cystisoma magna'               : 'Crustacea',
'Cystisoma pellucida'           : 'Crustacea',
'Decapoda'                      : 'Crustacea',
'Euphausia'                     : 'Crustacea',
'Euphausia pacifica'            : 'Crustacea',
'Euphausia 2'                   : 'Crustacea',
'Euphausiacea'                  : 'Crustacea',
'Euphausiidae'                  : 'Crustacea',
'Eusergestes'                   : 'Crustacea',
'Eusergestes similis'           : 'Crustacea',
'Galatheidae'                   : 'Crustacea',
'Gammaridea'                    : 'Crustacea',
'Gaussia princeps'              : 'Crustacea',
'Gnathophausia'                 : 'Crustacea',
'Hyperiidae'                    : 'Crustacea',
'Isopoda'                       : 'Crustacea',
'Lanceola'                      : 'Crustacea',
'Lanceolidae'                   : 'Crustacea',
'Lithodidae'                    : 'Crustacea',
'Munneurycope'                  : 'Crustacea',
'Munneurycope murrayi'          : 'Crustacea',
'Munnopsidae'                   : 'Crustacea',
'Munnopsis'                     : 'Crustacea',
'Munnopsoides'                  : 'Crustacea',
'Munnopsurus'                   : 'Crustacea',
'Mysida'                        : 'Crustacea',
'Mysidae'                       : 'Crustacea',
'Mysidae 2'                     : 'Crustacea',
'Neolithodes'                   : 'Crustacea',
'Oplophoridae'                  : 'Crustacea',
'Pandalidae'                    : 'Crustacea',
'Paralomis'                     : 'Crustacea',
'Paraphronima'                  : 'Crustacea',
'Paramunnopsis'                 : 'Crustacea',
'Paropsurus'                    : 'Crustacea',
'Pasiphaea'                     : 'Crustacea',
'Pasiphaeidae'                  : 'Crustacea',
'Phronima'                      : 'Crustacea',
'Polycheles'                    : 'Crustacea',
'Polychelidae 2'                : 'Crustacea',
'Scina'                         : 'Crustacea',
'Scinidae'                      : 'Crustacea',
'Scinoidea'                     : 'Crustacea',
'Scypholanceola'                : 'Crustacea',
'Sergestes'                     : 'Crustacea',
'Sergestes similis'             : 'Crustacea',
'Sergestidae'                   : 'Crustacea',
'Storthyngura'                  : 'Crustacea',
'Streetsia'                     : 'Crustacea',
'Hyperiidea'                    : 'Crustacea',
'Oxycephalidae'                 : 'Crustacea',
'Paracallisoma'                 : 'Crustacea',
'Phronimidae'                   : 'Crustacea',
'Nebalia'                       : 'Crustacea',
'Nebaliopsis'                   : 'Crustacea',
'Copepoda'                      : 'Crustacea',
'Euchaeta'                      : 'Crustacea',
'Euchirella'                    : 'Crustacea',
'Euchirella bitumida'           : 'Crustacea',
'Megacalanus'                   : 'Crustacea',
'Sapphirina'                    : 'Crustacea',
'Gigantocypris agassizii'       : 'Crustacea',
'Gigantocypris dracontovalis'   : 'Crustacea',
'Ostracoda'                     : 'Crustacea',
'Crustacea'                     : 'Crustacea',
'Acanthamunnopsis sp2@'         : 'Crustacea',
'Acanthamunnopsis sp3@'         : 'Crustacea',
'Llyria'                        : 'Ctenophora',
'Agmayeria tortuguensis@'       : 'Ctenophora',
'Benthic cteno@'                : 'Ctenophora',
'Black cydippid@'               : 'Ctenophora',
'Cteno four-spot@'              : 'Ctenophora',
'Ctenoceros sp.@'               : 'Ctenophora',
'Ctenophora'                    : 'Ctenophora',
'Liverlips cteno@'              : 'Ctenophora',
'Llyria copper@'                : 'Ctenophora',
'Llyria sp1@'                   : 'Ctenophora',
'Lobata sp2@'                   : 'Ctenophora',
'Nepheloctena red@'             : 'Ctenophora',
'Nepheloctena white@'           : 'Ctenophora',
'Orange cydippid@'              : 'Ctenophora',
'Peach cydippid@'               : 'Ctenophora',
'Pleurobrachia bachei'          : 'Ctenophora',
'Redgut cydippid@'              : 'Ctenophora',
'RedX cteno@'                   : 'Ctenophora',
'Vermillion lobate@'            : 'Ctenophora',
'Weird cteno@'                  : 'Ctenophora',
'Beroe'                         : 'Ctenophora',
'Beroe abyssicola'              : 'Ctenophora',
'Beroe cucumis'                 : 'Ctenophora',
'Beroe forskalii'               : 'Ctenophora',
'Beroe gracilis'                : 'Ctenophora',
'Beroida'                       : 'Ctenophora',
'Cestidae'                      : 'Ctenophora',
'Cestum veneris'                : 'Ctenophora',
'Velamen parallelum'            : 'Ctenophora',
'Aulacoctena'                   : 'Ctenophora',
'Bathyctena'                    : 'Ctenophora',
'Bathyctena chuni'              : 'Ctenophora',
'Euplokamis'                    : 'Ctenophora',
'Euplokamis dunlapae'           : 'Ctenophora',
'Haeckelia'                     : 'Ctenophora',
'Haeckelia rubra'               : 'Ctenophora',
'Lampea'                        : 'Ctenophora',
'Lampea pancerina'              : 'Ctenophora',
'Charistephane'                 : 'Ctenophora',
'Mertensiidae'                  : 'Ctenophora',
'Cydippida'                     : 'Ctenophora',
#'Hormiphora californiensis'    : 'Ctenophora',
'Hormiphora californensis'      : 'Ctenophora',
'Pleurobrachia'                 : 'Ctenophora',
'Bathocyroe'                    : 'Ctenophora',
'Bathocyroe fosteri'            : 'Ctenophora',
'Bolinopsis'                    : 'Ctenophora',
'Bolinopsis infundibulum'       : 'Ctenophora',
'Deiopea'                       : 'Ctenophora',
'Hormiphora californensis'      : 'Ctenophora',
'Kiyohimea usagi'               : 'Ctenophora',
'Lampocteis cruentiventer'      : 'Ctenophora',
'Leucothea'                     : 'Ctenophora',
'Lobata'                        : 'Ctenophora',
'Lyrocteis'                     : 'Ctenophora',
'Platyctenida'                  : 'Ctenophora',
'Tjalfiella'                    : 'Ctenophora',
'Tjalfiella tristoma'           : 'Ctenophora',
'Thalassocalyce inconstans'     : 'Ctenophora',
'Aporocidaris milleri'          : 'Echinoidea',
'Tromikosoma'                   : 'Echinoidea',
'Tromikosoma panamense'         : 'Echinoidea',
'Tromikosoma sp. 1'             : 'Echinoidea',
'Cystechinus loveni'            : 'Echinoidea',
'Cystocrepis setigera'          : 'Echinoidea',
'Echinocrepis rostrata'         : 'Echinoidea',
'Echinoidea'                    : 'Echinoidea',
'Paelopatides confundens'       : 'Holothuroidea',
'Pseudostichopus mollis'        : 'Holothuroidea',
'Synallactes'                   : 'Holothuroidea',
'Synallactidae'                 : 'Holothuroidea',
'Amperima robusta'              : 'Holothuroidea',
'Benthodytes'                   : 'Holothuroidea',
'Peniagone'                     : 'Holothuroidea',
'Psychropotes depressa'         : 'Holothuroidea',
'Scotoplanes'                   : 'Holothuroidea',
'Scotoplanes globosa'           : 'Holothuroidea',
'Pannychia moseleyi'            : 'Holothuroidea',
'Abyssocucumis'                 : 'Holothuroidea',
'Staurocucumis abyssorum'       : 'Holothuroidea',
'Holothuroidea sp. 1'           : 'Holothuroidea',
'Holothuroidea'                 : 'Holothuroidea',
'Holothurian sp. 2'             : 'Holothuroidea',
'Oneirophanta mutabilis'        : 'Holothuroidea',
'Asteroidea'                    : 'Asterozoa',
'Brisingida'                    : 'Asterozoa',
'Brisingidae'                   : 'Asterozoa',
'Ophiurida'                     : 'Ophiuroidea',
'Ophiuroidea'                   : 'Ophiuroidea',
'Pteraster'                     : 'Asterozoa',
'Pterasteridae'                 : 'Asterozoa',
'Echiura'                       : 'Echiura',
'Bathyraja cf. microtrachys'    : 'Fishes',
'Torquaratoridae sp. 1'         : 'Hemichordata',
'Enteropneusta'                 : 'Hemichordata',
'TorquaratoridaeB sp. 1'        : 'Hemichordata',
'Actinernus'                    : 'Hexacorallia',
'Actiniaria'                    : 'Hexacorallia',
'Dofleinia'                     : 'Hexacorallia',
'Hormathiidae'                  : 'Hexacorallia',
'Liponema brevicornis'          : 'Hexacorallia',
'Stomphia'                      : 'Hexacorallia',
'Bathypathes'                   : 'Hexacorallia',
'Ceriantharia'                  : 'Hexacorallia',
'Ceriantharia sp. 1'            : 'Hexacorallia',
'Corallimorpharia'              : 'Hexacorallia',
'Corallimorphidae'              : 'Hexacorallia',
'Hexacorallia'                  : 'Hexacorallia',
'Cerianthidae'                  : 'Hexacorallia',
'Zoanthidea'                    : 'Hexacorallia',
'Anthozoa'                      : 'Hexacorallia',
'Annatiara'                     : 'Hydromedusae',
'Anthomedusae'                  : 'Hydromedusae',
'Branchiocerianthus imperator'  : 'Hydroidolina',
'Bythotiara'                    : 'Hydromedusae',
'Bythotiara depressa'           : 'Hydromedusae',
'Calycopsidae'                  : 'Hydromedusae',
'Calycopsis'                    : 'Hydromedusae',
'Eumedusa'                      : 'Hydromedusae',
'Euphysa'                       : 'Hydromedusae',
'Euphysora valdiviae'           : 'Hydromedusae',
'Heterotiara minor'             : 'Hydromedusae',
'Leuckartiara'                  : 'Hydromedusae',
'Pandea'                        : 'Hydromedusae',
'Pandea rubra'                  : 'Hydromedusae',
'Pandeidae'                     : 'Hydromedusae',
'Polyorchis'                    : 'Hydromedusae',
'Aequorea'                      : 'Hydromedusae',
'Chromatonema rubrum'           : 'Hydromedusae',
'Earleria'                      : 'Hydromedusae',
'Earleria corachloeae'          : 'Hydromedusae',
'Eutima'                        : 'Hydromedusae',
'Eutonina indicans'             : 'Hydromedusae',
'Leptomedusae'                  : 'Hydromedusae',
'Mitrocoma cellularia'          : 'Hydromedusae',
'Modeeria rotunda'              : 'Hydromedusae',
'Octogonade'                    : 'Hydromedusae',
'Phialidium'                    : 'Hydromedusae',
'Ptychogena lactea'             : 'Hydromedusae',
'Tiaranna'                      : 'Hydromedusae',
'Tiarannidae'                   : 'Hydromedusae',
'Hydromedusae'                  : 'Hydromedusae',
'Aegina'                        : 'Hydromedusae',
'Aegina citrea'                 : 'Hydromedusae',
'Aegina rosea'                  : 'Hydromedusae',
'Aeginidae'                     : 'Hydromedusae',
'Aeginura'                      : 'Hydromedusae',
'Aeginura grimaldii'            : 'Hydromedusae',
'Cunina'                        : 'Hydromedusae',
'Halitrephes maasi'             : 'Hydromedusae',
'Narcomedusae'                  : 'Hydromedusae',
'Pegantha'                      : 'Hydromedusae',
'Solmaris'                      : 'Hydromedusae',
'Solmissus'                     : 'Hydromedusae',
'Solmissus incisa'              : 'Hydromedusae',
'Solmarisidae'                  : 'Hydromedusae',
'Solmissus marshalli'           : 'Hydromedusae',
'Solmundella'                   : 'Hydromedusae',
'Solmundella bitentaculata'     : 'Hydromedusae',
'Arctapodema'                   : 'Hydromedusae',
'Benthocodon'                   : 'Hydromedusae',
'Botrynema brucei'              : 'Hydromedusae',
'Colobonema'                    : 'Hydromedusae',
'Colobonema sericeum'           : 'Hydromedusae',
'Crossota'                      : 'Hydromedusae',
'Crossota alba'                 : 'Hydromedusae',
'Crossota millsae'              : 'Hydromedusae',
'Crossota rufobrunnea'          : 'Hydromedusae',
'Geryonia proboscidalis'        : 'Hydromedusae',
'Halicreas'                     : 'Hydromedusae',
'Halicreas minimum'             : 'Hydromedusae',
'Halicreatidae'                 : 'Hydromedusae',
'Haliscera'                     : 'Hydromedusae',
'Haliscera bigelowi'            : 'Hydromedusae',
'Haliscera conica'              : 'Hydromedusae',
'Halitrephes'                   : 'Hydromedusae',
'LRJ complex'                   : 'Hydromedusae',
'Liriope'                       : 'Hydromedusae',
'Liriope tetraphylla'           : 'Hydromedusae',
'Pantachogon haeckeli'          : 'Hydromedusae',
'Ptychogastria'                 : 'Hydromedusae',
'Ptychogastria polaris'         : 'Hydromedusae',
'Rhopalonema'                   : 'Hydromedusae',
'Rhopalonema funerarium'        : 'Hydromedusae',
'Rhopalonema velatum'           : 'Hydromedusae',
'Rhopalonematidae'              : 'Hydromedusae',
'Sminthea'                      : 'Hydromedusae',
'Tetrorchis'                    : 'Hydromedusae',
'Tetrorchis erythrogaster'      : 'Hydromedusae',
'Tetrorchis sp. A'              : 'Hydromedusae',
'Trachymedusae'                 : 'Hydromedusae',
'Voragonema'                    : 'Hydromedusae',
'Voragonema pedunculata'        : 'Hydromedusae',
'Hydrozoa'                      : 'Hydromedusae',
'Medusae'                       : 'Hydromedusae',
'Aegina bent-tentacle'          : 'Hydromedusae',
'Aegina bent-tentacle@'         : 'Hydromedusae',
'Aegina six-tentacle@'          : 'Hydromedusae',
'Aegina stubby@'                : 'Hydromedusae',
'Calycopsidae sp2@'             : 'Hydromedusae',
'Calycopsidae sp3@'             : 'Hydromedusae',
'Calycopsidae wrinkled@'        : 'Hydromedusae',
'Solmaris sp1@'                 : 'Hydromedusae',
'Bivalvia'                      : 'Mollusca',
'Solemyacea'                    : 'Mollusca',
'Neptunea-Buccinum Complex'     : 'Mollusca',
'Gastropoda'                    : 'Mollusca',
'Calliostoma'                   : 'Mollusca',
'Heteropoda'                    : 'Mollusca',
'Pterotrachea'                  : 'Mollusca',
'Neoloricata'                   : 'Mollusca',
'Nectonemertes'                 : 'Nemertea',
'Nectonemertes mirabilis'       : 'Nemertea',
'Nemertea'                      : 'Nemertea',
'Nemertea orange'               : 'Nemertea',
'Nemertea white'                : 'Nemertea',
'Phallonemertes'                : 'Nemertea',
'Alcyonacea'                    : 'Octocorallia',
'Anthomastus'                   : 'Octocorallia',
'Anthomastus ritteri'           : 'Octocorallia',
'Anthomastus robustus'          : 'Octocorallia',
'Isididae'                      : 'Octocorallia',
'Lepidisis'                     : 'Octocorallia',
'Primnoidae'                    : 'Octocorallia',
'Octocorallia'                  : 'Octocorallia',
'Distichoptilum gracile'        : 'Octocorallia',
'Pennatula californica'         : 'Octocorallia',
'Pennatulacea'                  : 'Octocorallia',
'Umbellula lindahli'            : 'Octocorallia',
'Umbellula sp. 1'               : 'Octocorallia',
'Virgularia'                    : 'Octocorallia',
'Macrocystis'                   : 'Algae',
'Laminariales'                  : 'Algae',
'Annelida'                      : 'Polychaeta',
'Chauvinella'                   : 'Polychaeta',
'Elvis worm@'                   : 'Polychaeta',
'Tomopteris redgut@'            : 'Polychaeta',
'Polychaeta'                    : 'Polychaeta',
'Harmothoe'                     : 'Polychaeta',
'Alciopidae'                    : 'Polychaeta',
'Aphroditidae'                  : 'Polychaeta',
'Lopadorhynchidae'              : 'Polychaeta',
'Onuphidae'                     : 'Polychaeta',
'Pelagobia longicirrata'        : 'Polychaeta',
'Polynoidae'                    : 'Polychaeta',
'Pontodora pelagica'            : 'Polychaeta',
'Tomopteridae'                  : 'Polychaeta',
'Tomopteris'                    : 'Polychaeta',
'Tomopteris nisseni'            : 'Polychaeta',
'Travisiopsis'                  : 'Polychaeta',
'Typhloscolecidae'              : 'Polychaeta',
'Ampharetidae'                  : 'Polychaeta',
'Chaetopterus pugaporcinus'     : 'Polychaeta',
'Flabelligeridae'               : 'Polychaeta',
'Flota vitjasi'                 : 'Polychaeta',
'Poeobius'                      : 'Polychaeta',
'Poeobius 2'                    : 'Polychaeta',
'Poeobius meseres'              : 'Polychaeta',
'Sabellidae'                    : 'Polychaeta',
'Serpulidae'                    : 'Polychaeta',
 'Syllidae'                     : 'Polychaeta',
'Swima'                         : 'Polychaeta',
 'Swima fulgida'                : 'Polychaeta',
'Swima bombiviridis'            : 'Polychaeta',
'Terebellidae'                  : 'Polychaeta',
'Maldane cristata'              : 'Polychaeta',
'Maldane '                      : 'Polychaeta',
'Asbestopluma'                  : 'Porifera',
'Chondrocladia'                 : 'Porifera',
'Cladorhizidae'                 : 'Porifera',
'Poecilosclerida'               : 'Porifera',
'Hexactinellida sp. 2'          : 'Porifera',
'Heterochone'                   : 'Porifera',
'Bathydorus'                    : 'Porifera',
'Caulophacus cyanae'            : 'Porifera',
'Saccocalyx pedunculatus'       : 'Porifera',
'Hexactinellida'                : 'Porifera',
'Chondrocladia sp. 3'           : 'Porifera',
'Porifera'                      : 'Porifera',
'Mystery Mollusc'               : 'Pteropoda', # (NOT REALLY, BUT...)
'Clione limacina'               : 'Pteropoda',
'Corolla'                       : 'Pteropoda',
'Creseis virgula'               : 'Pteropoda',
'Notobranchaea'                 : 'Pteropoda',
'Pseudothecosomata'             : 'Pteropoda',
'Thliptodon'                    : 'Pteropoda',
'Cavolinidae'                   : 'Pteropoda',
'Notobranchaea panda'           : 'Pteropoda',
'Pteropod'                      : 'Pteropoda',
'Thliptodon sp.@'               : 'Pteropoda',
'Pycnogonida'                   : 'Pycnogonida',
'Cercozoa'                      : 'Radiolaria',
'Egg rad@'                      : 'Radiolaria',
'Inside-out rad@'               : 'Radiolaria',
'Spider rad@'                   : 'Radiolaria',
'Tuscaretta aeronauta'          : 'Radiolaria',
'Polycystina'                   : 'Radiolaria',
'Radiozoa'                      : 'Radiolaria',
'Planktonetta'                  : 'Radiolaria',
'Tuscarantha'                   : 'Radiolaria',
'Tuscarantha braueri'           : 'Radiolaria',
'Tuscarantha luciae'            : 'Radiolaria',
'Tuscaretta globosa'            : 'Radiolaria',
'Tuscaridium cygneum'           : 'Radiolaria',
'Tuscarilla'                    : 'Radiolaria',
'Tuscarilla campanella'         : 'Radiolaria',
'Tuscarilla nationalis'         : 'Radiolaria',
'Tuscarilla similis'            : 'Radiolaria',
'Tuscarora'                     : 'Radiolaria',
'Tuscaroridae'                  : 'Radiolaria',
'Aulosphaera'                   : 'Radiolaria',
'Phaeodaria'                    : 'Radiolaria',
'Radiolaria'                    : 'Radiolaria',
'Bathysiphon'                   : 'Rhizaria',
'Foraminiferida'                : 'Foraminiferida',
'Hastigerinella digitata'       : 'Foraminiferida',
'Xenophyophorea'                : 'Rhizaria',
'Psamminida'                    : 'Rhizaria',
'Psamminidae'                   : 'Rhizaria',
'Atolla'                        : 'Scyphozoa',
'Atolla parva'                  : 'Scyphozoa',
'Atolla vanhoeffeni'            : 'Scyphozoa',
'Atolla wyvillei'               : 'Scyphozoa',
'Atorella'                      : 'Scyphozoa',
'Coronatae'                     : 'Scyphozoa',
'Nausithoe'                     : 'Scyphozoa',
'Nausithoe rubra'               : 'Scyphozoa',
'Paraphyllina'                  : 'Scyphozoa',
'Paraphyllina ransoni'          : 'Scyphozoa',
'Periphylla periphylla'         : 'Scyphozoa',
'Periphyllidae'                 : 'Scyphozoa',
'Periphyllopsis'                : 'Scyphozoa',
'Periphyllopsis galatheae'      : 'Scyphozoa',
'Chrysaora fuscescens'          : 'Scyphozoa',
'Aurelia aurita'                : 'Scyphozoa',
'Deepstaria enigmatica'         : 'Scyphozoa',
'Deepstaria reticulum'          : 'Scyphozoa',
'Phacellophora camtschatica'    : 'Scyphozoa',
'Poralia rufescens'             : 'Scyphozoa',
'Tiburonia granrojo'            : 'Scyphozoa',
'Bathyphysa conifera'           : 'Cystonect',
'Bathyphysa'                    : 'Cystonect',
'Calycophorae'                  : 'Calycophoran',
'Chuniphyes'                    : 'Calycophoran',
'Chuniphyes moserae'            : 'Calycophoran',
'Chuniphyes multidentata'       : 'Calycophoran',
'Clausophyes'                   : 'Calycophoran',
'Clausophyes moserae'           : 'Calycophoran',
'Clausophyidae'                 : 'Calycophoran',
'Craseoa lathetica'             : 'Calycophoran',
'Desmophyes'                    : 'Calycophoran',
'Desmophyes annectens'          : 'Calycophoran',
'Desmophyes haematogaster'      : 'Calycophoran',
'Dromalia alexandri'            : 'Rhodaliid',
'Gymnopraia lapislazula'        : 'Calycophoran',
'Kephyes ovata'                 : 'Calycophoran',
'Lensia'                        : 'Calycophoran',
'Lensia achilles'               : 'Calycophoran',
'Lensia conoidea'               : 'Calycophoran',
'Lensia havock'                 : 'Calycophoran',
'Lensia hostile'                : 'Calycophoran',
'Lensia multicristata'          : 'Calycophoran',
'Lilyopsis fluoracantha'        : 'Calycophoran',
'Maresearsia praeclara'         : 'Calycophoran',
'Mistoprayina'                  : 'Calycophoran',
'Nectadamas diomedeae'          : 'Calycophoran',
'Praya dubia'                   : 'Calycophoran',
'Prayidae'                      : 'Calycophoran',
'Prayinae'                      : 'Calycophoran',
'Rosacea'                       : 'Calycophoran',
'Sphaeronectes'                 : 'Calycophoran',
'Sphaeronectes christiansonae'  : 'Calycophoran',
'Sphaeronectes haddocki'        : 'Calycophoran',
'Sphaeronectes tiburonae'       : 'Calycophoran',
'Vogtia'                        : 'Calycophoran',
'Siphonophora'                  : 'Physonect',
'Apolemia'                      : 'Physonect',
'Bargmannia'                    : 'Physonect',
'Bargmannia amoena'             : 'Physonect',
'Bargmannia elongata'           : 'Physonect',
'Bargmannia lata'               : 'Physonect',
'Cordagalma'                    : 'Physonect',
'Erenna'                        : 'Physonect',
'Erenna cornuta'                : 'Physonect',
'Erenna richardi'               : 'Physonect',
'Crystallophyes amygdalina'     : 'Calycophoran',
'Erenna sirena'                 : 'Physonect',
'Erenna insidiator'             : 'Physonect',
'Forskalia'                     : 'Physonect',
'Frillagalma vityazi'           : 'Physonect',
'Halistemma'                    : 'Physonect',
'Lychnagalma'                   : 'Physonect',
'Lychnagalma utricularia'       : 'Physonect',
'Marrus'                        : 'Physonect',
'Marrus claudanielis'           : 'Physonect',
'Nanomia bijuga'                : 'Physonect',
'Physonectae'                   : 'Physonect',
'Physophora hydrostatica'       : 'Physonect',
'Resomia dunni'                 : 'Physonect',
'Resomia ornicephala'           : 'Physonect',
'Resomia persica'               : 'Physonect',
'Rhodaliidae'                   : 'Physonect',
'Rudjakovia plicata'            : 'Physonect',
'Siphonophorae'                 : 'Physonect',
'Stephanomia amphytridis '      : 'Physonect',
'Stephanomia amphytridis'       : 'Physonect',
'Thermopalia taraxaca'          : 'Rhodaliid',
'Apolemia purple@'              : 'Physonect',
'Apolemia shaggy@'              : 'Physonect',
'Apolemia white@'               : 'Physonect',
'Bargmannia wispy@'             : 'Physonect',
'Blue-green siph@'              : 'Calycophoran',
'Clausophyes missinglink@'      : 'Calycophoran',
'Cordagalma sp1@'               : 'Physonect',
'Cordagalma sp3@'               : 'Physonect',
'Erenna non-laciniata@'         : 'Physonect',
'Galaxy physonect@'             : 'Physonect',
'Gillia reticulata'             : 'Calycophoran',
'Lions mane@'                   : 'Physonect',
'Marrus orange@'                : 'Physonect',
'Marrus two-spot@'              : 'Physonect',
'Physonect galaxy@'             : 'Physonect',
'Rhodaliidae sp1@'              : 'Rhodaliid',
'Zigzag physonect@'             : 'Physonect',
'Bathochordaeus sinker'         : 'snow',
'larvacean house'               : 'snow',
'marine snow'                   : 'snow',
'mung'                          : 'snow',
'phytodetritus'                 : 'snow',
'sinker'                        : 'snow',
'Marine snow'                   : 'snow',
'Mung'                          : 'snow',
'Sinker'                        : 'snow',
'Alepocephalidae'               : 'Fishes',
'Anguilliformes'                : 'Fishes',
'Anotopterus pharao'            : 'Fishes',
'Argyropelecus affinis'         : 'Fishes',
'Aristostomias scintillans'     : 'Fishes',
'Avocettina'                    : 'Fishes',
'Avocettina bowersii'           : 'Fishes',
'Bathylagidae'                  : 'Fishes',
'Bathylagus'                    : 'Fishes',
'Bathylagus milleri'            : 'Fishes',
'Bathysaurus mollis'            : 'Fishes',
'Bothrocara brunneum'           : 'Fishes',
'Careproctus longifilis'        : 'Fishes',
'Cetomimiformes'                : 'Fishes',
'Chaenophryne'                  : 'Fishes',
'Chauliodus'                    : 'Fishes',
'Chauliodus macouni'            : 'Fishes',
'Chiasmodon'                    : 'Fishes',
'Chiasmodon niger'              : 'Fishes',
'Chiasmodontidae'               : 'Fishes',
'Coryphaenoides'                : 'Fishes',
'Coryphaenoides acrolepis'      : 'Fishes',
'Coryphaenoides filifer'        : 'Fishes',
'Coryphaenoides leptolepis'     : 'Fishes',
'Coryphaenoides pectoralis'     : 'Fishes',
'Cyclothone'                    : 'Fishes',
'Cyclothone pallida'            : 'Fishes',
'Cyema atrum'                   : 'Fishes',
'Engraulidae'                   : 'Fishes',
'Idiacanthinae'                 : 'Fishes',
'Idiacanthus'                   : 'Fishes',
'Leuroglossus stilbius'         : 'Fishes',
'Liparidae'                     : 'Fishes',
'Lycenchelys'                   : 'Fishes',
'Lycodapus'                     : 'Fishes',
'Lycodes'                       : 'Fishes',
'Macrouridae'                   : 'Fishes',
'Melamphaidae'                  : 'Fishes',
'Melanostigma pammelas'         : 'Fishes',
'Merluccius productus'          : 'Fishes',
'Myctophidae'                   : 'Fishes',
'Nemichthyidae'                 : 'Fishes',
'Nemichthys'                    : 'Fishes',
'Oneirodes'                     : 'Fishes',
'Ophidiidae'                    : 'Fishes',
'Ophidiiformes'                 : 'Fishes',
'Osteichthyes'                  : 'Fishes',
'Osteodiscus'                   : 'Fishes',
'Paralepididae'                 : 'Fishes',
'Paraliparis'                   : 'Fishes',
'Paraliparis dactylosus'        : 'Fishes',
'Paraliparis rosaceus'          : 'Fishes',
'Pleuronectiformes'             : 'Fishes',
'Pleuronectiformes 2'           : 'Fishes',
'Pseudobathylagus milleri'      : 'Fishes',
'Saccopharyngidae'              : 'Fishes',
'Sardinops'                     : 'Fishes',
'Scopelarchidae'                : 'Fishes',
'Serrivomer'                    : 'Fishes',
'Serrivomer sector'             : 'Fishes',
'Spectrunculus grandis'         : 'Fishes',
'Stenobrachius'                 : 'Fishes',
'Stenobrachius leucopsarus'     : 'Fishes',
'Sternoptychidae'               : 'Fishes',
'Sternoptyx'                    : 'Fishes',
'Stomiidae'                     : 'Fishes',
'Synodontidae'                  : 'Fishes',
'Tactostoma'                    : 'Fishes',
'Tactostoma macropus'           : 'Fishes',
'Talismania bifurcata'          : 'Fishes',
'Tarletonbeania crenularis'     : 'Fishes',
'Carangidae'                    : 'Fishes',
'Chaetodontidae'                : 'Fishes',
'Chauliodontinae'               : 'Fishes',
'Peprilus'                      : 'Fishes',
'Trachipterus'                  : 'Fishes',
'Trachipterus altivelis'        : 'Fishes',
'Prionace glauca'               : 'Fishes',
'Zoarcidae'                     : 'Fishes',
'Doliopsis'                     : 'Thaliacea',
'Urochordata'                   : 'Thaliacea',
'Dolioletta'                    : 'Thaliacea',
'Doliolida'                     : 'Thaliacea',
'Doliolula equus'               : 'Thaliacea',
'Doliopsidae'                   : 'Thaliacea',
'Paradoliopsis harbisoni'       : 'Thaliacea',
'Pseudusa'                      : 'Thaliacea',
'Pseudusa bostigrinus'          : 'Thaliacea',
'Thaliacea'                     : 'Thaliacea',
'Cyclosalpa'                    : 'Thaliacea',
'Salpa'                         : 'Thaliacea',
'Salpida'                       : 'Thaliacea',
'Thetys vagina'                 : 'Thaliacea',
'Vitreosalpa gemini'            : 'Thaliacea',
'Phyllospadix'                  : 'Tracheophyta',
'Coryphaenoides armatus-yaquinae complex' : 'Fishes',
'Actinopteri'				: 'Fishes', # Association data
'Hydrolagus colliei'		: 'Fishes',
'Hydrolagus melanophasma'	: 'Fishes',
'Icichthys lockingtoni'		: 'Fishes',
'Careproctus'				: 'Fishes',
'Leuroglossus'				: 'Fishes',
'Scombridae'				: 'Fishes',
'Lampanyctus'				: 'Fishes',
'Mola'						: 'Fishes',
'Merlucciidae'				: 'Fishes',
'Merluccius'				: 'Fishes',
'Myctophid'					: 'Fishes',
'Pseudobathylagus'			: 'Fishes',
'Stenobrachius'				: 'Fishes',
'Tarletonbeania'	   		: 'Fishes',
'Doryteuthis'				: 'Cephalopoda',
'Dosidicus'					: 'Cephalopoda',
'Loliginidae'				: 'Cephalopoda',
'Loligo'					: 'Cephalopoda',
'Onychoteuthidae'			: 'Cephalopoda',
'Caecosagitta'				: 'Chaetognatha',
'Pinnipedia'				: 'Pinnipedia',
'Eusergestes'				: 'Crustacea',
'Krill'						: 'Crustacea',
'Shrimp'					: 'Crustacea',
'Nanomia'					: 'Siphonophora',
'Praya'						: 'Siphonophora',
'Cnidaria'					: 'Scyphozoa',
'Phacellophora'				: 'Scyphozoa',
'Chrysaora'					: 'Scyphozoa',
'Scyphozoa'					: 'Scyphozoa',
'Earleria purpurea'			: 'Hydromedusae',
'Mitrocoma'					: 'Hydromedusae',
'Hormiphora'				: 'Ctenophora',
'Kiyohimea'					: 'Ctenophora',
'Lampocteis'				: 'Ctenophora',
'Thalassocalyce'			: 'Ctenophora',
'Thalassocalycida'			: 'Ctenophora',
'Cephalopyge'				: 'Pteropoda',
'Cephalopyge trematoides'	: 'Pteropoda',
'Phylliroe'					: 'Pteropoda',
'Pterotracheoidea'			: 'Pteropoda',
'Pterotrachea'				: 'Pteropoda',
'Pteropoda'					: 'Pteropoda',
'Pyrosoma'					: 'Thaliacea',
'Salp'						: 'Thaliacea',
'Vitreosalpa'				: 'Thaliacea',
'Lophiiformes'				: 'Fishes',
'Phronima sedentaria'		: 'Crustacea',
'Pleuroncodes planipes'		: 'Crustacea',
# ADDED May 2016
 'Abraliopsis'                       : 'Cephalopoda',
 'Abraliopsis felis'                 : 'Cephalopoda',
 'Cirrothauma'                       : 'Cephalopoda',
 'Cirrothauma murrayi'               : 'Cephalopoda',
 'Chiroteuthidae'                    : 'Cephalopoda',
 'Enteroctopus dofleini'             : 'Cephalopoda',
 'Grimpoteuthis sp. 5'               : 'Cephalopoda',
 'Haliphron atlanticus'              : 'Cephalopoda',
 'Bolitaenidae'                      : 'Cephalopoda',
 'Leachia danae'                     : 'Cephalopoda',
 'Octopoda'                          : 'Cephalopoda',
 'Oegopsida'                         : 'Cephalopoda',
 'Onychoteuthis borealijaponica'     : 'Cephalopoda',
 'Onykia robusta '                   : 'Cephalopoda',
 'Planctoteuthis'                    : 'Cephalopoda',
 'Planctoteuthis danae'              : 'Cephalopoda',
 'Stigmatoteuthis dofleini'          : 'Cephalopoda',
 'Archeterokrohnia docrickettsae'    : 'Chaetognatha',
 'Eukrohnia bathyantarctica'         : 'Chaetognatha',
 'Eukrohnia hamata'                  : 'Chaetognatha',
 'Heterokrohnia involucrum'          : 'Chaetognatha',
 'Sagittidae'                        : 'Chaetognatha',
 'Sagittidae sp. 1'                  : 'Chaetognatha',
 'Solidosagitta zetesios'            : 'Chaetognatha',
 'Acanthephyra'                      : 'Crustacea',
 'Boreomysis'                        : 'Crustacea',
 'Conchoecissa'                      : 'Crustacea',
 'Cyphocaris'                        : 'Crustacea',
 'Gaussia'                           : 'Crustacea',
 'Hymenodora frontalis'              : 'Crustacea',
 'Hymenopenaeus doris'               : 'Crustacea',
 'Lanceoloidea'                      : 'Crustacea',
 'Mimonectes'                        : 'Crustacea',
 'Munidopsidae'                      : 'Crustacea',
 'Munidopsis'                        : 'Crustacea',
 'Munnopsis abyssalis'               : 'Crustacea',
 'Mysidacea'                         : 'Crustacea',
 'Parasergestes halia'               : 'Crustacea',
 'Pasiphaea pacifica'                : 'Crustacea',
 'Sergia'                            : 'Crustacea',
 'Sergia phorca'                     : 'Crustacea',
 'Systellaspis'                      : 'Crustacea',
 'Charistephane fugiens'             : 'Ctenophora',
 'Euplokamidae'                      : 'Ctenophora',
 'Dryodora glandiformis'             : 'Ctenophora',
 'Mertensia'                         : 'Ctenophora',
 'Mertensiidae sp. A'                : 'Ctenophora',
 'Ocyropsis'                         : 'Ctenophora',
 'Platyctenida sp. 1'                : 'Ctenophora',
 'Foraminifera'                      : 'Foraminiferida',
 'Agalma'                            : 'Physonect',
 'Agalmatidae'                       : 'Physonect',
 'Apolemia lanosa'                   : 'Physonect',
 'Apolemia rubriversa'               : 'Physonect',
 'Crystallophyes'                    : 'Calycophoran',
 'Clausophyes tropica'               : 'Calycophoran',
 'Erenna laciniata'                  : 'Physonect',
 'Erenna sp. A'                      : 'Physonect',
 'Erenna sp. B'                      : 'Physonect',
 'Forskalia formosa'                 : 'Physonect',
 'Halistemma rubrum'                 : 'Physonect',
 'Lensia baryi'                      : 'Calycophoran',
 'Lensia hotspur'                    : 'Calycophoran',
 'Lilyopsis'                         : 'Calycophoran',
 'Marrus orthocanna'                 : 'Physonect',
 'Mistoprayina fragosa'              : 'Calycophoran',
 'Nanomia 2'                         : 'Physonect',
 'Nectadamas '                       : 'Calycophoran',
 'Nectopyramidinae'                  : 'Calycophoran',
 'Nectopyramis natans'               : 'Calycophoran',
 'Physonectae sp. 1'                 : 'Physonect',
 'Physophora gilmeri'                : 'Physonect',
 'Resomia'                           : 'Physonect',
 'Rhizophysa'                        : 'Cystonect',
 'Rudjakovia'                        : 'Physonect',
 'Stephalia'                         : 'Rhodaliid',
 'Stephalia dilata'                  : 'Rhodaliid',
 'Thermopalia'                       : 'Rhodaliid',
 'Vogtia serrata'                    : 'Calycophoran',
 'Collozoum'                         : 'Radiolaria',
 'Medusetta'                         : 'Radiolaria',
 'Medusettidae'                      : 'Radiolaria',
 'Solenosphaera'                     : 'Radiolaria',
 'Tuscaretta'                        : 'Radiolaria',
 'Aglantha'                          : 'Hydromedusae',
 'Aglantha digitale'                 : 'Hydromedusae',
 'Aglaura'                           : 'Hydromedusae',
 'Calycopsis simulans'               : 'Hydromedusae',
 'Chiarella'                         : 'Hydromedusae',
 'Chiarella centripetalis'           : 'Hydromedusae',
 'Cuninidae'                         : 'Hydromedusae',
 'Euphysa japonica'                  : 'Hydromedusae',
 'Euphysora'                         : 'Hydromedusae',
 'Euphysora gigantea'                : 'Hydromedusae',
 'Geryonia'                          : 'Hydromedusae',
 'Melicertum octocostatum'           : 'Hydromedusae',
 'Mitrocomidae'                      : 'Hydromedusae',
 'Neoturris'                         : 'Hydromedusae',
 'Pegantha clara'                    : 'Hydromedusae',
 'Sarsia'                            : 'Hydromedusae',
 'Scrippsia'                         : 'Hydromedusae',
 'Scrippsia pacifica'                : 'Hydromedusae',
 'Tetraplatia'                       : 'Hydromedusae',
 'Tetraplatia volitans'              : 'Hydromedusae',
 'Tiaropsidium'                      : 'Hydromedusae',
 'Tiaropsidium kelseyi'              : 'Hydromedusae',
 'Vampyrocrossota'                   : 'Hydromedusae',
 'Vampyrocrossota childressi'        : 'Hydromedusae',
 'Tima'                              : 'Hydromedusae',
 'Actinopterygii'                    : 'Fishes',
 'Antimora'                          : 'Fishes',
 'Anoplogaster cornuta'              : 'Fishes',
 'Argyropelecus'                     : 'Fishes',
 'Bathylagoides wesethi'             : 'Fishes',
 'Cyematidae'                        : 'Fishes',
 'Chaenophryne longiceps'            : 'Fishes',
 'Eurypharynx pelecanoides'          : 'Fishes',
 'Gadella jordani'                   : 'Fishes',
 'Halosauridae'                      : 'Fishes',
 'Idiacanthus antrostomus'           : 'Fishes',
 'Leptocephalus-2'                   : 'Fishes',
 'Macropinna microstoma'             : 'Fishes',
 'Melanostigma'                      : 'Fishes',
 'Microstomus pacificus'             : 'Fishes',
 'Mola mola'                         : 'Fishes',
 'Melamphaes'                        : 'Fishes',
 'Oneirodes acanthias'               : 'Fishes',
 'Saccopharynx'                      : 'Fishes',
 'Saccopharynx lavenbergi'           : 'Fishes',
 'Sardinops sagax'                   : 'Fishes',
 'Sebastes'                          : 'Fishes',
 'Scopelarchus'                      : 'Fishes',
 'Scopelogadus mizolepis bispinosus' : 'Fishes',
 'Sternoptyx diaphana'               : 'Fishes',
 'Stomias'                           : 'Fishes',
 'Stomias atriventer'                : 'Fishes',
 'Stomiiformes'                      : 'Fishes',
 'Triphoturus mexicanus'             : 'Fishes',
 'Atolla gigantea'                   : 'Scyphozoa',
 'Atorella octogonus'                : 'Scyphozoa',
 'Deepstaria'                        : 'Scyphozoa',
 'Phacellophora camtschatica '       : 'Scyphozoa',
 'Stellamedusa'                      : 'Scyphozoa',
 'Stellamedusa ventana'              : 'Scyphozoa',
 'Tiburonia'                         : 'Scyphozoa',
 'Ulmaridae'                         : 'Scyphozoa',
 'Bathochordaeus charon'             : 'Appendicularia',
 'Bathochordaeus sp. A'              : 'Appendicularia',
 'Bathochordaeus stygius'            : 'Appendicularia',
 'Fritillariinae'                    : 'Appendicularia',
 'Doliolida 2'                       : 'Thaliacea', 
 'Doliolinetta'                      : 'Thaliacea', 
 'Doliolina (Doliolinetta)'          : 'Thaliacea',
 'Helicosalpa'                       : 'Thaliacea', 
 'Pegea confoederata'                : 'Thaliacea', 
 'Paradoliopsidae'                   : 'Thaliacea', 
 'Paradoliopsis'                     : 'Thaliacea', 
 'Pyrosoma atlanticum'               : 'Thaliacea', 
 'Salpa fusiformis'                  : 'Thaliacea', 
 'Salpa maxima'                      : 'Thaliacea', 
 'Thetys'                            : 'Thaliacea', 
 'Cavolinia'                         : 'Pteropoda',
 'Cephalopyge trematoides'           : 'Pteropoda',
 'Cardiapoda placenta'               : 'Pteropoda',
 'Carinaria'                         : 'Pteropoda',
 'Carinaria cristata'                : 'Pteropoda',
 'Carinaria japonica'                : 'Pteropoda',
 'Clio'                              : 'Pteropoda',
 'Clio cuspidata'                    : 'Pteropoda',
 'Clio polita'                       : 'Pteropoda',
 'Clio pyramidata'                   : 'Pteropoda',
 'Clione'                            : 'Pteropoda',
 'Corolla spectabilis'               : 'Pteropoda',
 'Creseis'                           : 'Pteropoda',
 'Gymnosomata'                       : 'Pteropoda',
 'Mollusca'                          : 'Pteropoda',
 'Pterotracheidae'                   : 'Pteropoda',
 'Thecosomata'                       : 'Pteropoda',
 'Alciopa'                           : 'Polychaeta',
 'Allapasus sp. 3'                   : 'Polychaeta',
 'Rhynchonereella'                   : 'Polychaeta',
 'Chauvinelia'                       : 'Polychaeta',
 'Pneumodermatidae'                  : 'Pteropoda',
 'Pneumodermatidae '                 : 'Pteropoda',
 'Pneumodermopsis'                   : 'Pteropoda',
 'Hyalocylis'                        : 'Pteropoda',
 'Phyllodocida'                      : 'Polychaeta',
 'Chrysaora melanaster'              : 'Scyphozoa', 
 'Cirroteuthis muelleri'             : 'Cephalopoda',
 'Diphyidae'                         : 'Calycophoran',
 'Bolinopsidae'                      : 'Ctenophora',
  'Holothuria'                       : 'Holothuroidea',
   'Laetmogone'                      : 'Holothuroidea',
    'Lysianassidae'                  : 'Crustacea',
 'Squalus suckleyi'                 : 'Fishes',
  'Tomopterid eggcase'              : 'Polychaeta',
  'Bathochordaeus mcnutti'  : 'Appendicularia',
  'Bathophilus'             : 'Fishes',
  'Bathophilus filifer'     : 'Fishes',
  'Boreomysis californica'  : 'Crustacea',
  'Bregmaceros bathymaster' : 'Fishes',
  'Cyclosalpa affinis '     : 'Thaliacea',
  'Diplophos pacificus'     : 'Fishes',
  'Thliptodon sp. A'        : 'Pteropoda',
  'Creseidae'               : 'Pteropoda',
  'Ditropichthys storeri'   : 'Fishes',
  'Gonatopsis octopedatus'  : 'Cephalopoda',
  'Gonatus pyros'           : 'Cephalopoda',
  'Histioteuthidae'         : 'Cephalopoda',
  'Nebaliidae'              : 'Crustacea',
  'Kali'                    : 'Fishes',
  'Neoturris breviconis'    : 'Hydromedusae',
  'Nettastoma parviceps'    : 'Fishes',
  'Peraclidae'              : 'Pteropoda',
  'Procymbulia'             : 'Pteropoda',
  'Ptychogena hyperborea'   : 'Hydromedusae',
  # ADDED AUG 2019
  'Collodaria'                       : "Radiolaria", #Changed Mar 2023
  'Gleba'                            : "Pteropoda",
  'Clupeiformes'                     : "Fishes",
  'Myctophiformes'                   : "Fishes",
  'Talismania'                       : "Fishes",
  'Stomiinae'                        : "Fishes",
  'Cyema'                            : "Fishes",
  'Coryphaenoides armatus'           : "Fishes",
  'Poromitra'                        : "Fishes",
  'Poromitra crassiceps'             : "Fishes",
  'Lycodapus fierasfer'              : "Fishes",
  'Clio andreae'                     : "Pteropoda",
  'Crossota pedunculata'             : "Hydromedusae",
  'Bougainvilliidae'                 : "Hydromedusae",
  'Octogonade mediterranea'          : "Hydromedusae",
  'Melicertum'                       : "Hydromedusae",
  'Aequorea aequorea'                : "Hydromedusae",
  'Dipleurosoma typicum'             : "Hydromedusae",
  'Chrysaora colorata'               : "Scyphozoa",
  'Nausithoidae'                     : "Scyphozoa",
  'Doliolum'                         : "Thaliacea",
  'Doliopsidina'                     : "Thaliacea",
  'Pyrosomida'                       : "Thaliacea",
  'Salpidae'                         : "Thaliacea",
  'Helicosalpa virgula'              : "Thaliacea",
  'Pegea'                            : "Thaliacea",
  'Cyclosalpa bakeri'                : "Thaliacea",
  'Solidosagitta'                    : "Chaetognatha",
  'Eukrohniidae'                     : "Chaetognatha",
  'Squalus'                          : "Fishes",
  'Thalassicolla'                    : "Radiolaria",
  'Aulacoctena acuminata'            : "Ctenophora",
  'Cydippida sp. A'                  : "Ctenophora",
  'Deiopea kaloktenota'              : "Ctenophora",
  'Ctenophora sp. A'                 : "Ctenophora",
  'Thalassocalycidae'                : "Ctenophora",
  'Mertensiidae sp. B'               : "Ctenophora",
  'Ocyropsidae'                      : "Ctenophora",
  'Cranchia scabra'                  : "Cephalopoda",
  'Berryteuthis'                     : "Cephalopoda",
  'Berryteuthis anonychus'           : "Cephalopoda",
  'Doryteuthis (Amerigo) opalescens' : "Cephalopoda",
  'Grimalditeuthis bonplandi'        : "Cephalopoda",
  'Onychoteuthis'                    : "Cephalopoda",
  'Onykia robusta'                   : "Cephalopoda",
  'Helicocranchia'                   : "Cephalopoda",
  'Stigmatoteuthis'                  : "Cephalopoda",
  'Taonius borealis'                 : "Cephalopoda",
  'Forskalia edwardsi'               : "Physonect",
  'Apolemiidae'                      : "Physonect",
  'Tottonophyes enigmatica'          : "Calycophoran",
  'Prayidae sp. 1'                   : "Calycophoran",
  'Cordagalma abyssorum'             : "Physonect",
  'Cordagalma bimaculatum'           : "Physonect",
  'Cordagalma isocarrei'             : "Physonect",
  'Cordagalma rugosum'               : "Physonect",
  'Polynoinae'                       : "Polychaeta",
  'Lopadorrhynchus'                  : "Polychaeta", 
  'Pannychia sp. 1'                  : "Holothuroidea",
  'Phorcosergia'                     : "Crustacea",
  'Phorcosergia phorca'              : "Crustacea",
  #Added March 2022
  'Bathyspadella'                    : 'Chaetognatha',
  'Alepisaurus ferox'                : 'Fishes',
  'Anoplogaster'                     : 'Fishes',
  'Anoplopoma'                       : 'Fishes', #benthic
  'Anotopterus'                      : 'Fishes', #benthic
  'Bargmannia profunda'              : 'Physonect',
  'Bargmannia stenotes'              : 'Physonect',
  'Bathyctenidae'                    : 'Ctenophora',
  'Bathylagus pacificus'             : 'Fishes',
  'Benthalbella'                     : 'Fishes', #benthic
  'Benthesicymidae'                  : 'Crustacea', #benthic
  'Birsteiniamysis inermis'          : 'Crustacea',#benthic
  'Bothidae'                         : 'Fishes',#benthic
  'Calanidae'                        : 'Crustacea',
  'Caristiidae'                      : 'Fishes', 
  'Centrolophidae'                   : 'Fishes',
  'Cerataspis monstrosus'            : 'Crustacea',#benthic
  'Cetostoma'                        : 'Fishes',
  'Chiasmodon subniger'              : 'Fishes',
  'Cololabis saira'                  : 'Fishes', 
  'Cyclosalpa affinis'               : 'Thaliacea',
  'Cydippida sp. B'                  : 'Ctenophora',
  'Cystonectae'                      : 'Siphonophora',
  'Danaphos oculatus'                : 'Fishes',
  'Derepodichthys'                   : 'Fishes', #benthic
  'Diaphus'                          : 'Fishes',
  'Dryodora'                         : 'Ctenophora',
  'Eumalacostraca'                   : 'Crustacea',
  'Eurycope'                         : 'Crustacea',
  'Forskalia edwardsii'              : 'Physonect',
  'Gennadas'                         : 'Crustacea',
  'Grimalditeuthis'                  : 'Cephalopoda',
  'Gymnothorax'                      : 'Fishes',
  'Hippopodiidae'                    : 'Calycophoran',
  'Hymenodora'                       : 'Crustacea',
  'Icelinus fimbriatus'              : 'Fishes',#benthic
  'Icichthys'                        : 'Fishes',
  'Kali kerberti'                    : 'Fishes',
  'Leptostraca'                      : 'Crustacea',
  'Lipolagus ochotensis'             : 'Fishes',
  'Lophogastridae'                   : 'Crustacea',
  'Lycodinae'                        : 'Fishes',
  'Magnisudis atlantica'             : 'Fishes',
  'Mastigoteuthis'                   : 'Cephalopoda',
  'Mastigotragus'                    : 'Cephalopoda',
  'Megacalanidae'                    : 'Crustacea',
  'Melanostomiinae'                  : 'Fishes',
  'Munnopsinae'                      : 'Crustacea',
  'Muusoctopus robustus'             : 'Cephalopoda',#benthic
  'Nannobrachium regale'             : 'Fishes',
  'Nannobrachium ritteri'            : 'Fishes',
  'Nebaliopsididae'                  : 'Crustacea',
  'Nectoliparis'                     : 'Fishes',
  'Nectoliparis pelagicus'           : 'Fishes',
  'Neolithodes diomedeae'            : 'Fishes',
  'Oneirodidae'                      : 'Fishes',
  'Osmeriformes'                     : 'Fishes',
  'Pandalus amplus'                  : 'Crustacea',
  'Paraliparis sp. 1'                : 'Fishes',
  'Parapaguridae'                    : 'Crustacea',
  'Parvilux'                         : 'Fishes',
  'Parvilux ingens'                  : 'Fishes',
  'Regalecus glesne'                 : 'Fishes',
  'Resomiidae'                       : 'Physonect',
  'Sagittoidea'                      : 'Chaetognatha',
  'Salmonidae'                       : 'Fishes',
  'Salmoniformes'                    : 'Fishes',
  'Scopelogadus'                     : 'Fishes',
  'Scopelosaurus'                    : 'Fishes',
  'Sebastolobinae'                   : 'Fishes', #benthic
  'Soestia zonaria'                  : 'Thaliacea',
  'Sphyraena argentea'               : 'Fishes', #benthic
  'Sphyraenidae'                     : 'Fishes', #benthic
  'Sternostylus'                     : 'Crustacea',#benthic
  'Sternostylus iaspis'              : 'Crustacea',#benthic
  'Tetragonuridae'                   : 'Fishes',
  'Teuthowenia'                      : 'Cephalopoda',
  'Tiaropsidae'                      : 'Hydromedusae',
  'Tottonophyidae'                   : 'Physonect',
  'Trachipteridae'                   : 'Fishes',
  'Vanhoeffenura'                    : 'Crustacea',
  'Vanhoeffenura pulchra'            : 'Crustacea',
  'Vitreledonella'                   : 'Cephalopoda',
  ## ADDED MARCH 2023
  "Actinostoloidea"                         : "Hexacorallia",
"Aeolidiidae sp. 1"                       : "Mollusca",
"Agnatha"                                 : "Fishes",
"Alariaceae"                              : "Algae",
"Alepisaurus ferox"                       : "Fishes",
"Allapasus aurantiacus"                   : "Hemichordata",
"Allapasus sp. 1"                         : "Hemichordata",
"Anotopterus"                             : "Fishes",
"Atollidae"                               : "Scyphozoa",
'Pelagia'                                 : 'Scyphozoa',
'Pelagia colorata'                        : 'Scyphozoa',
'Pelagia noctiluca'                       : 'Scyphozoa',
"Cyanea capillata"                        : "Scyphozoa",
"Cyanea"                                  : "Scyphozoa",
"Alciopini" : "Polychaeta",
"Tomopteris septentrionalis" : "Polychaeta",
"Barbourisia"                             : "Fishes",
"Bargmannia profunda"                     : "Physonect",
"Bargmannia stenotes"                     : "Physonect",
"Bathyctenidae"                           : "Ctenophora",
"Bathydorus laevis pseudospinosus"        : "Porifera",
"Bathylagus pacificus"                    : "Fishes",
"Bathysiphon major"                       : "Foraminiferida",
"Benthalbella"                            : "Fishes",
"Benthesicymidae"                         : "Crustacea",
"Bentheuphausia amblyops"                 : "Crustacea",
"Benthocodon pedunculata"                 : "Hydromedusae",
"Beringraja rhina"                        : "Fishes",
"Birsteiniamysis inermis"                 : "Crustacea",
"Calanidae"                               : "Crustacea",
"Calyptogena extenta"                     : "Mollusca",
"Cavoliniidae"                            : "Pteropoda",
"Centrolophidae"                          : "Fishes", #B
"Cestida"                                 : "Ctenophora",
"Cetostoma"                               : "Fishes",
"chauliodus"                              : "Fishes",
"Chondrocladia (Symmetrocladia) lyra"     : "Porifera",
"Chordata"                                : "XXX",
"Cololabis saira"                         : "Fishes",
"Culeolus barryi"                         : "Ascidiacea",
"Culeolus sp. 2"                          : "Ascidiacea",
"Cyclosalpa affinis"                      : "Thaliacea",
"Cystonectae"                             : "Siphonophora",
"Danaphos oculatus"                       : "Fishes",
"Demospongiae sp. 1"                      : "Porifera",
"Derepodichthys"                          : "Fishes",
"Diaphus"                                 : "Fishes",
"Docosaccus maculatus"                    : "Porifera",
"Enhydra"                                 : "Mammalia",
"Epizoanthus"                             : "Hexacorallia",
"Euryalida"                               : "Ophiuroidea",
"Eurycope"                                : "Crustacea",
"Euthecosomata"                           : "Pteropoda",
"Exocoelactis"                            : "Hexacorallia",
"Fauveliopsidae"                          : "Polychaeta",
"Filifera"                                : "Hydroidolina",
"Flota flabelligera"                      : "Polychaeta",
"Fritillaria rex"                         : "Appendicularia",
"Fungiacyathus (Bathyactis) marenzelleri" : "Hexacorallia",
"gastropoda"                              : "Mollusca",
"Gennadas"                                : "Crustacea",
"Gigantactis"                             : "Fishes",
"Gorgoniidae"                             : "Octocorallia",
"Grimalditeuthis"                         : "Cephalopoda",
"Gymnothorax"                             : "Fishes",
'Hexanchus griseus'	                      : 'Fishes',
"Holothuria (Vaneyothuria) zacae"         : "Holothuroidea",
"Holothuroidea sp. 8"                     : "Holothuroidea",
"Hymenodora"                              : "Crustacea",
"Hyperiidea"                              : "Crustacea",
"Icichthys"                               : "Fishes",
"Kali kerberti"                           : "Fishes",
"Kowalevskia"                             : "Appendicularia",
"Kowalevskiidae"                          : "Appendicularia",
"Lamberticrinus"                          : "Crinoidea",
"Leptostraca"                             : "Crustacea",
"Lipolagus ochotensis"                    : "Fishes",
"Lissodelphis borealis"                   : "Mammalia",
"Mastigoteuthis"                          : "Cephalopoda",
"Mastigotragus"                           : "Cephalopoda",
"Megacalanidae"                           : "Crustacea",
"Melanocetus"                             : "Fishes",
"Melanostomiinae"                         : "Fishes",
"Munnopsinae"                             : "Crustacea",
"Muusoctopus robustus"                    : "Cephalopoda",
"Mycale"                                  : "Porifera",
"Nannobrachium regale"                    : "Fishes",
"Nannobrachium ritteri"                   : "Fishes",
"Nebaliopsididae"                         : "Crustacea",
"Nectoliparis"                            : "Fishes",
"Nectoliparis pelagicus"                  : "Fishes",
"Nectonemertidae"                         : "Nemertea",
"Nemertea sp. A"                          : "Nemertea",
"Neolithodes diomedeae"                   : "Crustacea",
"Oligobrachia"                            : "Polychaeta",
"Oneirodidae"                             : "Fishes",
"Ophiomusa"                               : "Ophiuroidea",
"Paracallisoma"                           : "Crustacea",
"Parahyocrinus"                           : "Crinoidea",
"Paraliparis sp. 1"                       : "Fishes",
"Parvilux"                                : "Fishes",
"Parvilux ingens"                         : "Fishes",
"Pectis"                                  : "Hydromedusae",
"Pectis pedunculata"                      : "Hydromedusae",
"Phaeoconchida"                           : "Rhizaria",
"Psamminidae sp. 2"                       : "Foraminiferida",
"Resomiidae"                              : "Siphonophora",
"Sabellida"                               : "Polychaeta",
"Sagittoidea"                             : "Chaetognatha",
"Scopelogadus"                            : "Fishes",
"Scopelosaurus"                           : "Fishes",
"Scorpaenidae"                            : "Fishes",
"Squillidae"                              : "Crustacea",
"Sternaspidae"                            : "Polychaeta",
"Sternostylus iaspis"                     : "Crustacea",
"Stomotoca atra"                          : "Hydromedusae",
"Stylephorus chordatus"                   : "Fishes",
"Tetragonuridae"                          : "Fishes",
"Teuthowenia"                             : "Cephalopoda",
"Tiaropsidae"                             : "Hydromedusae",
"Trachipteridae"                          : "Fishes",
"Tubularia"                               : "Hydroidolina",
"Tuscaridium"                             : "Radiolaria",
"Vanhoeffenura"                           : "Crustacea",
"Vanhoeffenura pulchra"                   : "Crustacea",
"Vitreledonella"                          : "Cephalopoda",
"Kiyohimeidae" : "Ctenophora",
"Tjalfiellidae" : "Ctenophora",
"Carcharhinidae" : "Fishes",
"Gonostomatidae" : "Fishes",
"Hexanchus griseus" : "Fishes",
"Amphinema" : "Hydromedusae",
"Benthocodon pedunculata" : "Hydromedusae",
"Catablema" : "Hydromedusae",
"Colobonema apicatum" : "Hydromedusae",
"Pectis" : "Hydromedusae",
"Pectis pedunculata" : "Hydromedusae",
"Megaptera novaeangliae" : "Mammalia",
"Phoca" : "Mammalia",
'Atorella octogonos':"Scyphozoa",
'Calocarides quinqueseriatus':"Crustacea",
 'Cerataspis':"Crustacea",
 'Heterocarpus sp. 1':"Crustacea",
 'Leptoderma ospesca':"Fishes",
 'Pennatuloidea':"Octocorallia",
 'Physonectae sp. 3':"Siphonophora"
}
# END of concept to phylum list

concept_names = list(ConceptToPhylum.keys())

concept_args = [f"--include-concept '{concept}'" for concept in concept_names]
# Create a command line with --include-concept for each concept
cmd = "m3-download generate" \
       f"{' '.join(concept_args)} " \
       "--exclude-group 'ROV:pending-verifications' " \
       "--exclude-activity 'unspecified' " \
       "--exclude-project 'ML-Tracking' " \
       "/mnt/ML_SCRATCH/M3/images /mnt/ML_SCRATCH/M3/xml"

print(cmd)